docs: scribblings/xdsmith.scrbl
	cd docs; \
	scribble --redirect-main http://docs.racket-lang.org/ +m ../scribblings/xdsmith.scrbl; \
	scribble --pdf --redirect-main http://docs.racket-lang.org/ +m ../scribblings/xdsmith.scrbl
